environment:
  matrix:
    - TOXENV: py38
      COV_FAIL_UNDER: 60
install:
  - pip install tox codecov
build: false
test_script:
  - tox -- -vv tests/test_github.py tests/test_bitbucket.py tests/test_gitlab.py tests/test_pagure.py tests/test_db.py tests/test_caching.py
  - codecov
skip_branch_with_pr: true
